package smtp

import (
	"crypto/tls"
	"fmt"

	"github.com/akhil-datla/maildruid/internal/config"
	"github.com/matcornic/hermes/v2"
	gomail "gopkg.in/mail.v2"
)

// Sender sends emails via SMTP.
type Sender struct {
	cfg    config.SMTPConfig
	hermes hermes.Hermes
}

// New creates a new email sender.
func New(cfg config.SMTPConfig) *Sender {
	return &Sender{
		cfg: cfg,
		hermes: hermes.Hermes{
			Product: hermes.Product{
				Name:      "MailDruid",
				Link:      "https://github.com/akhil-datla/maildruid",
				Copyright: "MailDruid - Automated Email Summarization",
			},
		},
	}
}

// SendSummary sends a summary email with an optional word cloud attachment.
func (s *Sender) SendSummary(to, name string, tags []string, summary, wordCloudPath, errMsg string) error {
	m := gomail.NewMessage()
	m.SetHeader("From", s.cfg.Email)
	m.SetHeader("To", to)
	m.SetHeader("Subject", "MailDruid - Your Email Summary")

	intros := make([]string, 0, 3)
	if len(tags) > 0 {
		intros = append(intros, fmt.Sprintf("Here is your email summary for: %v", tags))
	}
	if summary != "" {
		intros = append(intros, summary)
	}
	if errMsg != "" {
		intros = append(intros, errMsg)
	}

	email := hermes.Email{
		Body: hermes.Body{
			Name:      name,
			Signature: "Regards",
			Intros:    intros,
			Outros: []string{
				"This summary was automatically generated by MailDruid.",
			},
		},
	}

	body, err := s.hermes.GenerateHTML(email)
	if err != nil {
		return fmt.Errorf("generating email HTML: %w", err)
	}

	m.SetBody("text/html", body)
	if wordCloudPath != "" {
		m.Embed(wordCloudPath)
	}

	d := gomail.NewDialer(s.cfg.Host, s.cfg.Port, s.cfg.Email, s.cfg.Password)
	d.TLSConfig = &tls.Config{ServerName: s.cfg.Host}

	if err := d.DialAndSend(m); err != nil {
		return fmt.Errorf("sending email: %w", err)
	}
	return nil
}
